### ISSUE TITLE
Problem with ElvUI_AddOnSkins: PallyPower

### ISSUE THREAD

**Issue by Vitoshka** [ElvUI-WotLK/ElvUI_AddOnSkins#97]
The same problem as with [ElvUi - TBC](https://github.com/ElvUI-TBC/ElvUI_AddOnSkins/issues/46)

[Addon skin PallyPower](https://gyazo.com/c0f3921581c2e8b976f9832ec63343f3) does not allow changing the scale of the frame of buffs and the frame of the config.
If I disable this skin ElvUi (PallyPower), then everything works fine.
Fix this plz)
Thx.

**Comment by Vitoshka** [comment]
https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/issues/88#issue-332985588

**Comment by Loaal** [comment]
Scaling of frames will broke 1 pixel borders (make 2px border or even disappear on one of sides), because of it scale option was initially disabled.

After one of last commits scale options was hidden from addon menu:
https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/commit/99423ef1e4a78234ab9093b2e2b9aa0de86c7115#diff-d0346496407c81d2fb06df0098c7c62aR18

Skin works as intended, if you want some changes feel free to open new issue.
